name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - uses: jwlawson/actions-setup-cmake@v1.9
    
    - name: build
      run: |
        mkdir -p build
        cmake -DCMAKE_BUILD_TYPE=Release -B build
        cmake --build build
        
    - name: exporting artefacts
      uses: actions/upload-artifact@v2
      with:
        name: fugue-plugins
        path: |
          build/fugue.dll
          build/fugue64.dll
