name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - uses: jwlawson/actions-setup-cmake@v1.9
    
    - name: build
      run: |
        mkdir -p build
        cmake -B build
        cmake --build build --config Release
        
    - name: exporting artefacts
      uses: actions/upload-artifact@v2
      with:
        name: fugue-plugins
        path: |
          build\Release\fugue.dll
          build\Release\fugue64.dll
